version: "3.8"

services:
  db:
    container_name: addressbook-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./database/config/init:/docker-entrypoint-initdb.d/
      - ./database/db:/var/lib/postgresql/data

  adminer:
    container_name: addressbook-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db:
    driver: local
